databases:
  - name: pictweet
    databaseName: pictweet
    user: pictweet
    region: ohio
    plan: free

services:
  - type: web
    name: pictweet
    env: python
    region: ohio
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pictweet
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

    autoDeploy: true